name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set up ChromeDriver
      run: |
        # Remove any existing ChromeDriver
        if (Test-Path "C:\drivers\chocolatey\bin\chromedriver.exe") {
          Remove-Item "C:\drivers\chocolatey\bin\chromedriver.exe"
        }
        # Download and install the latest ChromeDriver
        $chromeDriverVersion = Invoke-RestMethod https://chromedriver.storage.googleapis.com/LATEST_RELEASE
        Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/$chromeDriverVersion/chromedriver_win32.zip" -OutFile chromedriver_win32.zip
        Expand-Archive -Path chromedriver_win32.zip -DestinationPath C:\drivers\chocolatey\bin
        [System.IO.File]::Move('C:\drivers\chocolatey\bin\chromedriver.exe', 'C:\drivers\chocolatey\bin\chromedriver.exe')

    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Run tests
      run: |
        mvn test
