name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        java-version: ['11']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: temurin

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: C:\Users\runneradmin\.m2\repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install Google Chrome
      run: |
        Invoke-WebRequest -Uri https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -OutFile google-chrome-stable_current_amd64.deb
        Invoke-WebRequest -Uri https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip -OutFile chromedriver_win32.zip
        Expand-Archive -Path chromedriver_win32.zip -DestinationPath C:\drivers
        [System.IO.File]::Move('chromedriver.exe', 'C:\drivers\chromedriver.exe')

    - name: Build and test with Maven
      run: mvn clean install

    - name: Run tests with Maven
      run: mvn test

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports
        path: target\surefire-reports\*
